apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rhoar-nodejs
  annotations:
    openshift.io/display-name: OpenShift Application Runtimes Node.js
    description: >
      Build and run Node.js applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/openshift/source-to-image/blob/master/README.md.
spec:
  tags:
    - name: '8.x'
      annotations:
        openshift.io/display-name: OpenShift Application Runtimes Node.js
        description: >
          Build and run Node.js 8.x applications on RHEL 7.
        iconClass: icon-nodejs
        sampleRepo: 'https://github.com/bucharest-gold/nodejs-rest-http.git'
        tags: 'builder,node,nodejs,node.js'
        version: 8.9.4
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/rhoar-nodejs/nodejs-8'
